### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by ScorpionIbm**
I'm a hobbyist trying my way suggesting changing the keyword to something easier than stretching to "$" sign maybe "~" or "!" would do or a "b" as my change suggests

### CODE REVIEW

**Comment by brainfoolong** [comment]
Thanks for making this request but i'll not implement this because it will break the usage for all users. It's kinda annoying for people that use this all day long and now it just changes for no reason. Unfortunetely there is now way for a user to modify this key-binding to the own needs. I understand your point, but i cannot do this.

**Comment by ScorpionIbm** [comment]
So can you just upload another version with an easier keyword and tell the users about it?

**Comment by brainfoolong** [comment]
Way too much work, requires a new store entry, new extension id, etc... Than i have to put in some sort of notification for users that another (same) extension exist if they wish another keybind. All for just a keybind switch... I don't see this happen.

**Comment by ScorpionIbm** [comment]
I forked and edited this for my personal use I just wanted this to be on the store so I don't have to deal with it being disabled every time I open chrome. I don't have a store account and thought you could help thanks.

**Comment by brainfoolong** [comment]
Sorry, i cannot change such a core thing for one user only. The next comes and say this new keybind is not that what it should be.  To have 2 extensions in a store requires double amount of work and resources. Every google dev account is limited to a specific amount of extensions.

**Pull request closed without merging**
