### PR TITLE
Update background.js

### PR DESCRIPTION
**Pull request by ScorpionIbm**
Remove interval to allow the extension to idle I don't know the use of polling for this every second

### CODE REVIEW

**Comment by brainfoolong** [comment]
Can't do that. The option can be changed on another page `options.html`, therefore the interval exist. I agree that isn't the best way in terms of idle handling, but this way will break the feature entirely. I should find a more elegant way, when i have time for it.

**Comment by ScorpionIbm** [comment]
So can't you just make it poll for it once when the setting changes.
I just noticed that when you change the option from allowed to not allowed it syncs after some time but not the opposite

**Comment by brainfoolong** [comment]
There will be some way, i currently don't know what i will do, not very familar with the code anymore.

**Comment by ScorpionIbm** [comment]
This is solved if the extension goes to idle it reloads the settings again.
Will try to find a way (other than waiting for the addon to idle or restarting chrome) and commit

**Comment by ScorpionIbm** [comment]
Found some work around adding the storage command to the search function so it gets the settings with every search change

**Comment by brainfoolong** [comment]
This look a lot better, i'll merge that soon and have a look at this.

**Comment by brainfoolong** [comment]
Merged but with some preview i found a better handling for that.

**Comment by ScorpionIbm** [comment]
Glad that I made you look into this thoroughly

**Pull request merged**
