### PR TITLE
Support fuzzy search on title as well.

### PR DESCRIPTION
**Pull request by lazywei**

### CODE REVIEW

**Comment by brainfoolong** [comment]
Thanks for the contribution. I'll merge this later, i want to add it optional and deactivated per default with an option in the (currently not existing) settings to activate it.

**Comment by lazywei** [comment]
sounds reasonable
thanks :+1:

**Comment by brainfoolong** [comment]
Merged and added an option for that. Can you test it if this work as you have expected it?

**Comment by lazywei** [comment]
yeah it works as expected

**Comment by brainfoolong** [comment]
Great. Release in chrome webstore will follow in next days.

**Pull request merged**
